import { DemoScenario } from '../types/index.js';

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: 'scenario_1',
    title: 'Scenario 1: High Confidence Match (Maggi + Coke)',
    description: 'Customer orders 2 Maggi and 1 Coke, pays ₹80 via QR. Perfect match and instant reconciliation.',
    audioFileName: 'scenario_1_maggi_coke.wav',
    transcript: 'Bhaiya 2 Maggi aur ek Coke dena. Kitna hua? Assi rupaye.',
    language: 'hi',
    expectedProducts: [
      { name: 'Maggi 2-Min Noodles', quantity: 2, unitPrice: 15 },
      { name: 'Coca-Cola 500ml', quantity: 1, unitPrice: 50 },
    ],
    paymentAmount: 80,
    expectedOutcome: 'MATCHED',
    confidence: 97,
    notes: 'Amount exact (₹80), items resolved, confidence 97%.',
  },
  {
    id: 'scenario_2',
    title: 'Scenario 2: Multi-Item Basket (Pepsi + Chips + Chocolate)',
    description: 'Customer purchases 1 Pepsi, 2 Chips, and 1 Chocolate for ₹120.',
    audioFileName: 'scenario_2_pepsi_chips.wav',
    transcript: 'Ek Pepsi, do chips aur ek chocolate dena. Kitna hua bhaiya? Ek sau bees rupaye.',
    language: 'hi',
    expectedProducts: [
      { name: 'Pepsi 500ml', quantity: 1, unitPrice: 40 },
      { name: 'Lay’s Classic Salted', quantity: 2, unitPrice: 20 },
      { name: 'Cadbury Dairy Milk', quantity: 1, unitPrice: 40 },
    ],
    paymentAmount: 120,
    expectedOutcome: 'MATCHED',
    confidence: 95,
    notes: 'Multi-category basket matching total ₹120.',
  },
  {
    id: 'scenario_3',
    title: 'Scenario 3: Discrepancy & Low Confidence (Confirmation Required)',
    description: 'Customer orders 2 Pepsi + 1 Coke (₹130) but payment received is ₹180. Triggers merchant confirmation flag.',
    audioFileName: 'scenario_3_discrepancy.wav',
    transcript: 'Do Pepsi aur ek Coke dena.',
    language: 'hi',
    expectedProducts: [
      { name: 'Pepsi 500ml', quantity: 2, unitPrice: 40 },
      { name: 'Coca-Cola 500ml', quantity: 1, unitPrice: 50 },
    ],
    paymentAmount: 180,
    expectedOutcome: 'CONFIRMATION_REQUIRED',
    confidence: 65,
    notes: 'Demonstrates safeguard: expected ₹130, received ₹180. Flags confirmation.',
  },
  {
    id: 'scenario_4',
    title: 'Scenario 4: Lost Sales Signal (Pepsi Out of Stock)',
    description: 'Customer requests Pepsi, merchant says out of stock. Logs unfulfilled demand signal.',
    audioFileName: 'scenario_4_lost_sale.wav',
    transcript: 'Bhaiya Pepsi hai kya? Nahi, Pepsi khatam ho gayi.',
    language: 'hi',
    expectedProducts: [],
    paymentAmount: 0,
    expectedOutcome: 'LOST_SALE',
    confidence: 92,
    notes: 'Identifies lost sale event and increases Pepsi demand analytics.',
  },
  {
    id: 'scenario_5',
    title: 'Scenario 5: Essential Grocery (Bread + Milk)',
    description: 'Customer buys morning essentials: 1 packet Bread + 1 packet Amul Milk for ₹95.',
    audioFileName: 'scenario_5_bread_milk.wav',
    transcript: 'Ek packet bread aur ek packet Amul Taaza doodh dena.',
    language: 'hi',
    expectedProducts: [
      { name: 'Harvest Gold White Bread', quantity: 1, unitPrice: 45 },
      { name: 'Amul Taaza Milk 500ml', quantity: 1, unitPrice: 50 },
    ],
    paymentAmount: 95,
    expectedOutcome: 'MATCHED',
    confidence: 96,
    notes: 'Daily staple transaction reconciliation.',
  },
];
